databases:
  - name: pawfect_match
    databaseName: paw_db
    user: paw_user

services:
  - type: web
    name: pawfect_match_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paw_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false