require 'csv'

question1 = Question.create(content: 'What size dog do you prefer?', description: 'Small ( less than 22lbs ) | Medium ( 22lbs - 55lbs ) | Large ( 55lbs - 115lbs ) | Very large ( greater than 115lbs )')
answer_choice1 = AnswerChoice.create(text: 'Any', value: 1)
answer_choice2 = AnswerChoice.create(text: 'Small ( less than 22lbs )', value: 2)
answer_choice3 = AnswerChoice.create(text: 'Medium ( 22lbs - 55lbs )', value: 3)
answer_choice4 = AnswerChoice.create(text: 'Large ( 55lbs - 115lbs )', value: 4)
answer_choice5 = AnswerChoice.create(text: 'Very Large ( greater than 115lbs )', value: 5)
QuestionAnswerChoice.create(question_id: question1.id, answer_choice_id: answer_choice1.id)
QuestionAnswerChoice.create(question_id: question1.id, answer_choice_id: answer_choice2.id)
QuestionAnswerChoice.create(question_id: question1.id, answer_choice_id: answer_choice3.id)
QuestionAnswerChoice.create(question_id: question1.id, answer_choice_id: answer_choice4.id)
QuestionAnswerChoice.create(question_id: question1.id, answer_choice_id: answer_choice5.id)

question2 = Question.create(content: 'Will your dog be around close friends and family?')
answer_choice6 = AnswerChoice.create(text: 'Yes', value: 1)
answer_choice7 = AnswerChoice.create(text: 'No', value: 0)
QuestionAnswerChoice.create(question_id: question2.id, answer_choice_id: answer_choice6.id)
QuestionAnswerChoice.create(question_id: question2.id, answer_choice_id: answer_choice7.id)

question3 = Question.create(content: 'Do you have children or will your dog be around children?')
answer_choice8 = AnswerChoice.create(text: 'Yes', value: 1)
answer_choice9 = AnswerChoice.create(text: 'No', value: 0)
QuestionAnswerChoice.create(question_id: question3.id, answer_choice_id: answer_choice8.id)
QuestionAnswerChoice.create(question_id: question3.id, answer_choice_id: answer_choice9.id)

question4 = Question.create(content: 'Do you have other dogs/animals in your home?')
answer_choice10 = AnswerChoice.create(text: 'Yes', value: 1)
answer_choice11 = AnswerChoice.create(text: 'No', value: 0)
QuestionAnswerChoice.create(question_id: question4.id, answer_choice_id: answer_choice10.id)
QuestionAnswerChoice.create(question_id: question4.id, answer_choice_id: answer_choice11.id)

question5 = Question.create(content: 'How much shedding is acceptable to you?')
answer_choice12 = AnswerChoice.create(text: 'No shedding at all', value: 1)
answer_choice13 = AnswerChoice.create(text: 'I don\'t mind a tiny bit of shedding', value: 2)
answer_choice14 = AnswerChoice.create(text: 'A medium level of shedding is okay', value: 3)
answer_choice15 = AnswerChoice.create(text: 'High amounts of shedding does not bother me', value: 4)
answer_choice16 = AnswerChoice.create(text: 'I am fine with hair everywhere', value: 5)
QuestionAnswerChoice.create(question_id: question5.id, answer_choice_id: answer_choice12.id)
QuestionAnswerChoice.create(question_id: question5.id, answer_choice_id: answer_choice13.id)
QuestionAnswerChoice.create(question_id: question5.id, answer_choice_id: answer_choice14.id)
QuestionAnswerChoice.create(question_id: question5.id, answer_choice_id: answer_choice15.id)
QuestionAnswerChoice.create(question_id: question5.id, answer_choice_id: answer_choice16.id)

question6 = Question.create(content: 'How much grooming are you able to provide for you dog?', description: 'Some dog breeds require a lot of grooming')
answer_choice17 = AnswerChoice.create(text: 'Monthly', value: 1)
answer_choice18 = AnswerChoice.create(text: 'A couple of times a month', value: 2)
answer_choice19 = AnswerChoice.create(text: 'Every week', value: 3)
answer_choice20 = AnswerChoice.create(text: 'Multiple times a week', value: 4)
answer_choice21 = AnswerChoice.create(text: 'Every day', value: 5)
QuestionAnswerChoice.create(question_id: question6.id, answer_choice_id: answer_choice17.id)
QuestionAnswerChoice.create(question_id: question6.id, answer_choice_id: answer_choice18.id)
QuestionAnswerChoice.create(question_id: question6.id, answer_choice_id: answer_choice19.id)
QuestionAnswerChoice.create(question_id: question6.id, answer_choice_id: answer_choice20.id)
QuestionAnswerChoice.create(question_id: question6.id, answer_choice_id: answer_choice21.id)

question7 = Question.create(content: 'How much drooling could you tolerate?')
answer_choice22 = AnswerChoice.create(text: 'I do not want a dog that drools', value: 1)
answer_choice23 = AnswerChoice.create(text: 'A little bit of drool', value: 2)
answer_choice24 = AnswerChoice.create(text: 'Medium amounts of drool', value: 3)
answer_choice25 = AnswerChoice.create(text: 'Higher than normal levels of drool', value: 4)
answer_choice26 = AnswerChoice.create(text: 'Waterfalls of drool does not bother me', value: 5)
QuestionAnswerChoice.create(question_id: question7.id, answer_choice_id: answer_choice22.id)
QuestionAnswerChoice.create(question_id: question7.id, answer_choice_id: answer_choice23.id)
QuestionAnswerChoice.create(question_id: question7.id, answer_choice_id: answer_choice24.id)
QuestionAnswerChoice.create(question_id: question7.id, answer_choice_id: answer_choice25.id)
QuestionAnswerChoice.create(question_id: question7.id, answer_choice_id: answer_choice26.id)

question8 = Question.create(content: 'Will your dog be around strangers often?')
answer_choice27 = AnswerChoice.create(text: 'Yes', value: 1)
answer_choice28 = AnswerChoice.create(text: 'No', value: 0)
QuestionAnswerChoice.create(question_id: question8.id, answer_choice_id: answer_choice27.id)
QuestionAnswerChoice.create(question_id: question8.id, answer_choice_id: answer_choice28.id)

question9 = Question.create(content: 'How much playfulness is acceptable?')
answer_choice29 = AnswerChoice.create(text: 'I do not want a playful dog', value: 1)
answer_choice30 = AnswerChoice.create(text: 'A little bit of play', value: 2)
answer_choice31 = AnswerChoice.create(text: 'A normal amount of playfulness', value: 3)
answer_choice32 = AnswerChoice.create(text: 'Higher than normal playfulness', value: 4)
answer_choice33 = AnswerChoice.create(text: 'I love a playful dog', value: 5)
QuestionAnswerChoice.create(question_id: question9.id, answer_choice_id: answer_choice29.id)
QuestionAnswerChoice.create(question_id: question9.id, answer_choice_id: answer_choice30.id)
QuestionAnswerChoice.create(question_id: question9.id, answer_choice_id: answer_choice31.id)
QuestionAnswerChoice.create(question_id: question9.id, answer_choice_id: answer_choice32.id)
QuestionAnswerChoice.create(question_id: question9.id, answer_choice_id: answer_choice33.id)

question10 = Question.create(content: 'Do you want your dog to be protective?')
answer_choice34 = AnswerChoice.create(text: 'Yes', value: 1)
answer_choice35 = AnswerChoice.create(text: 'No', value: 0)
QuestionAnswerChoice.create(question_id: question10.id, answer_choice_id: answer_choice34.id)
QuestionAnswerChoice.create(question_id: question10.id, answer_choice_id: answer_choice35.id)

question11 = Question.create(content: 'How much traveling will you be doing with your dog?')
answer_choice36 = AnswerChoice.create(text: 'Never', value: 1)
answer_choice37 = AnswerChoice.create(text: 'Rarely', value: 2)
answer_choice38 = AnswerChoice.create(text: 'On occasion', value: 3)
answer_choice39 = AnswerChoice.create(text: 'Often', value: 4)
answer_choice40 = AnswerChoice.create(text: 'All of the time', value: 5)
QuestionAnswerChoice.create(question_id: question11.id, answer_choice_id: answer_choice36.id)
QuestionAnswerChoice.create(question_id: question11.id, answer_choice_id: answer_choice37.id)
QuestionAnswerChoice.create(question_id: question11.id, answer_choice_id: answer_choice38.id)
QuestionAnswerChoice.create(question_id: question11.id, answer_choice_id: answer_choice39.id)
QuestionAnswerChoice.create(question_id: question11.id, answer_choice_id: answer_choice40.id)

question12 = Question.create(content: 'How trainable do you want your dog to be?')
answer_choice41 = AnswerChoice.create(text: 'Very stubborn', value: 1)
answer_choice42 = AnswerChoice.create(text: 'Stubborn', value: 2)
answer_choice43 = AnswerChoice.create(text: 'Somewhat trainable', value: 3)
answer_choice44 = AnswerChoice.create(text: 'Trainable', value: 4)
answer_choice45 = AnswerChoice.create(text: 'Highly trainable', value: 5)
QuestionAnswerChoice.create(question_id: question12.id, answer_choice_id: answer_choice41.id)
QuestionAnswerChoice.create(question_id: question12.id, answer_choice_id: answer_choice42.id)
QuestionAnswerChoice.create(question_id: question12.id, answer_choice_id: answer_choice43.id)
QuestionAnswerChoice.create(question_id: question12.id, answer_choice_id: answer_choice44.id)
QuestionAnswerChoice.create(question_id: question12.id, answer_choice_id: answer_choice45.id)

question13 = Question.create(content: 'How energetic of a dog is tolerable for you?')
answer_choice46 = AnswerChoice.create(text: 'Calm', value: 1)
answer_choice47 = AnswerChoice.create(text: 'Low energy', value: 2)
answer_choice48 = AnswerChoice.create(text: 'Normal', value: 3)
answer_choice49 = AnswerChoice.create(text: 'Energetic', value: 4)
answer_choice50 = AnswerChoice.create(text: 'Very Energetic', value: 5)
QuestionAnswerChoice.create(question_id: question13.id, answer_choice_id: answer_choice46.id)
QuestionAnswerChoice.create(question_id: question13.id, answer_choice_id: answer_choice47.id)
QuestionAnswerChoice.create(question_id: question13.id, answer_choice_id: answer_choice48.id)
QuestionAnswerChoice.create(question_id: question13.id, answer_choice_id: answer_choice49.id)
QuestionAnswerChoice.create(question_id: question13.id, answer_choice_id: answer_choice50.id)

question14 = Question.create(content: 'How much barking can you put up with?')
answer_choice51 = AnswerChoice.create(text: 'None', value: 1)
answer_choice52 = AnswerChoice.create(text: 'Very little', value: 2)
answer_choice53 = AnswerChoice.create(text: 'Moderate amount', value: 3)
answer_choice54 = AnswerChoice.create(text: 'Frequent', value: 4)
answer_choice55 = AnswerChoice.create(text: 'Very frequent', value: 5)
QuestionAnswerChoice.create(question_id: question14.id, answer_choice_id: answer_choice51.id)
QuestionAnswerChoice.create(question_id: question14.id, answer_choice_id: answer_choice52.id)
QuestionAnswerChoice.create(question_id: question14.id, answer_choice_id: answer_choice53.id)
QuestionAnswerChoice.create(question_id: question14.id, answer_choice_id: answer_choice54.id)
QuestionAnswerChoice.create(question_id: question14.id, answer_choice_id: answer_choice55.id)

question15 = Question.create(content: 'How much mental stimulation can/will you provide for your dog?')
answer_choice56 = AnswerChoice.create(text: 'None', value: 1)
answer_choice57 = AnswerChoice.create(text: 'Very little', value: 2)
answer_choice58 = AnswerChoice.create(text: 'Moderate amount', value: 3)
answer_choice59 = AnswerChoice.create(text: 'High amount', value: 4)
answer_choice60 = AnswerChoice.create(text: 'Very high amount', value: 5)
QuestionAnswerChoice.create(question_id: question15.id, answer_choice_id: answer_choice56.id)
QuestionAnswerChoice.create(question_id: question15.id, answer_choice_id: answer_choice57.id)
QuestionAnswerChoice.create(question_id: question15.id, answer_choice_id: answer_choice58.id)
QuestionAnswerChoice.create(question_id: question15.id, answer_choice_id: answer_choice59.id)
QuestionAnswerChoice.create(question_id: question15.id, answer_choice_id: answer_choice60.id)

def import_dogs_csv
  csv_text = File.read('public/dog-data-cleaned.csv')
  csv = CSV.parse(csv_text, :headers => true)
  csv.each do |row|
    Dog.create!(row.to_hash)
  end
end

import_dogs_csv